misldy_top/urls.py
from django.contrib import admin
from django.urls import path, include
from captcha.views import captcha_refresh

urlpatterns = [
    path('', include('ylogin.urls', namespace='ylogin')),
    path('polls/', include('polls.urls', namespace='polls')),
    path('admin/', admin.site.urls),
    path('captcha', include('captcha.urls')),   # 生成验证码
    path('refresh/', captcha_refresh),          # 点击可以刷新验证码
]

polls/urls.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2021/4/26 09:33
# software: PyCharm
from  django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

ylogin/urls.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2021/4/26 15:23
# software: PyCharm
from django.urls import path

from . import views

app_name = 'ylogin'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.logout, name='logout'),
]

ylogin/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    """ 用户表 """
    gender = (
        ('male', '男'),
        ('female', '女')
    )
    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=32, choices=gender, default="男")
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['c_time']
        verbose_name = '用户'
        verbose_name_plural = '用户'

ylogin/forms.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2021/5/17 17:06
# software: PyCharm
from django import forms
from captcha.fields import CaptchaField
from .models import User


class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField(label='验证码')


class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    username = forms.CharField(required=True, error_messages={'required': '邮箱不能为空！'}, label="用户名", max_length=128,
                               min_length=6, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(required=True, error_messages={'required': '密码不能为空！'}, label="密码", max_length=256,
                                min_length=6, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(required=True, error_messages={'required': '确认密码不能为空！'}, label="确认密码", max_length=256,
                                min_length=6, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, error_messages={'required': '邮箱不能为空！'}, label="邮箱地址",
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)
    captcha = CaptchaField(required=True, error_messages={'required': '验证码不能为空！'}, label='验证码')

ylogin/views.py
from django.shortcuts import render, redirect
from .models import User
from django.views import generic
import hashlib

from .forms import UserForm, RegisterForm


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'ylogin/index.html'

    def get_queryset(self):
        return


class LoginView(generic.FormView):
    model = User
    template_name = 'ylogin/login.html'
    form_class = UserForm

    def get(self, request, *args, **kwargs):
        if request.session.get('is_login', None):
            return redirect("/")
        else:
            login_form = self.form_class()
            return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        login_form = self.form_class(request.POST)
        message = "请检查填写的内容！"
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            try:
                user = User.objects.get(name=username)
            except:
                message = "用户名不存在！"
            else:
                if user.password == hash_code(password):
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name
                    return redirect('/')
                else:
                    message = "密码不正确！"
        return render(request, self.template_name, locals())


class RegisterView(generic.CreateView):
    model = User
    template_name = 'ylogin/register.html'
    form_class = RegisterForm

    def get(self, request, *args, **kwargs):
        if request.session.get('is_login', None):
            return redirect("/")
        else:
            register_form = self.form_class()
            return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        register_form = self.form_class(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():  # 获取数据
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            if password1 != password2:  # 判断两次密码是否相同
                message = "两次输入的密码不同！"
            else:
                same_name_user = User.objects.filter(name=username)
                same_email_user = User.objects.filter(email=email)
                if same_name_user:  # 用户名唯一
                    message = '用户已经存在，请重新选择用户名！'
                elif same_email_user:  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                else:
                    # 当一切都OK的情况下，创建新用户
                    new_user = User.objects.create()
                    new_user.name = username
                    new_user.password = hash_code(password1)
                    new_user.email = email
                    new_user.sex = sex
                    new_user.save()
                    return redirect('/login/')  # 自动跳转到登录页面
        return render(request, self.template_name, locals())


# 注销
def logout(request):
    print(request.POST.get('next_href'))
    if not request.session.get('is_login', None):
        return redirect('/')

    request.session.flush()

    return redirect('/')


def hash_code(s, salt='mysite_login'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()

ylogin/templates/ylogin_base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.4.1-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
</head>
<body>
{#  <section>#}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav"
                    aria-expanded="false">
                <span class="sr-only">切换导航条</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">misldy.top</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'ylogin:index' %}">主页</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.is_login %}
                    <li><a href="#">当前在线：{{ request.session.user_name }}</a></li>
                    <li><a href="{% url 'ylogin:logout' %}">登出</a></li>
                {% else %}
                    <li><a href="{% url 'ylogin:login' %}">登录</a></li>
                    <li><a href="{% url 'ylogin:register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'JS/jquery-3.5.1.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
{#  </section>#}
</body>

{# 刷新验证码的脚本 #}
<script>
        $('.captcha').click(function () {
            $.getJSON('/captcha/refresh/',function (result) {
                $('.captcha').attr('src',result['image_url']);
                $('#id_captcha_0').val(result['key']);
            });
        });
</script>

</html>